=== netspective/sparx-2001/Sparx/web-shared/resources/edi/formats/OBOE/ansi/transactionSetRules.dtd
<!-- OBOE release 1.5.0 -->
<!ELEMENT transactionSet (table+)>
<!ATTLIST transactionSet name CDATA #REQUIRED>
<!ATTLIST transactionSet id CDATA #REQUIRED>
<!ATTLIST transactionSet revision CDATA #IMPLIED>
<!ATTLIST transactionSet functionalGroup CDATA #IMPLIED>
<!ATTLIST transactionSet description CDATA #IMPLIED>
<!ATTLIST transactionSet xmlTag CDATA #IMPLIED >
<!ELEMENT table (segment*)>
<!ATTLIST table section (header | detail | summary) "header">
<!ELEMENT segment (segment*, (compositeDE?, dataElement?)*)*>
<!ATTLIST segment name CDATA #REQUIRED>
<!ATTLIST segment id CDATA #REQUIRED>
<!ATTLIST segment sequence CDATA #REQUIRED>
<!ATTLIST segment description CDATA #IMPLIED>
<!ATTLIST segment occurs CDATA  #IMPLIED>
<!ATTLIST segment required (M | O | C) "M">
<!ATTLIST segment xmlTag CDATA  #IMPLIED>
<!ELEMENT compositeDE (dataElement)+>
<!ATTLIST compositeDE name CDATA #REQUIRED>
<!ATTLIST compositeDE id CDATA #REQUIRED>
<!ATTLIST compositeDE description CDATA #IMPLIED>
<!ATTLIST compositeDE sequence CDATA #IMPLIED>
<!ATTLIST compositeDE required CDATA #IMPLIED>
<!ATTLIST compositeDE xmlTag CDATA #IMPLIED>
<!ELEMENT dataElement EMPTY>
<!ATTLIST dataElement name CDATA #REQUIRED>
<!ATTLIST dataElement id CDATA #REQUIRED>
<!ATTLIST dataElement type CDATA #REQUIRED>
<!ATTLIST dataElement sequence CDATA #IMPLIED>
<!ATTLIST dataElement required CDATA #IMPLIED>
<!ATTLIST dataElement description CDATA #IMPLIED>
<!ATTLIST dataElement minLength CDATA #REQUIRED>
<!ATTLIST dataElement maxLength CDATA #REQUIRED>
<!ATTLIST dataElement xmlTag CDATA  #IMPLIED>

=== netspective/sparx-2001/Sparx/web-shared/resources/edi/formats/OBOE/ansi/271.xml
<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE transactionSet SYSTEM "transactionSetRules.dtd">
<!-- Revision 2.5.0 data/OBOE, docs, February 25, 2002, -->
<transactionSet name="Eligibility, Coverage or Benefit Information" id="271"
  revision="004010"
  functionalGroup="HB"
  description="This Draft Standard for Trial Use contains the format and establishes the data contents of the Eligibility, Coverage or Benefit Information Transaction Set (271) for use within the context of an Electronic Data Interchange (EDI) environment. This transaction set can be used to communicate information about or changes to eligibility, coverage or benefits from information sources (such as - insurers, sponsors, payors) to information receivers (such as - physicians, hospitals, repair facilities, third party administrators, governmental agencies). This information includes but is not limited to: benefit status, explanation of benefits, coverages, dependent coverage level, effective dates, amounts for co-insurance, co-pays, deductibles, exclusions and limitations."
  xmlTag="EligibilityCoverageOrBenefitInformation">
    <table section="header">
        <segment name="Transaction Set Header" id="ST"
          description="To indicate the start of a transaction set and to assign a control number"
          sequence="10"
          occurs="1"
          required='M'
          xmlTag="TransactionSetHeader">
            <dataElement name="Transaction Set Identifier Code" id="143"
              sequence="1"
              description="Code uniquely identifying a Transaction Set"
              type="ID" required="M"
              minLength="3" maxLength="3"
              idListFile="IDList143.xml"
              xmlTag="transactionSetIdentifierCode"/>
            <dataElement name="Transaction Set Control Number" id="329"
              sequence="2"
              description="Identifying control number that must be unique within the transaction set functional group assigned by the originator for a transaction set"
              type="AN" required="M"
              minLength="4" maxLength="9"
              xmlTag="transactionSetControlNumber"/>
        </segment>
        <segment name="Beginning of Hierarchical Transaction" id="BHT"
          description="To define the business hierarchical structure of the transaction set and identify the business application purpose and reference data, i.e., number, date, and time"
          sequence="20"
          occurs="1"
          required='M'
          xmlTag="BeginningOfHierarchicalTransaction">
            <dataElement name="Hierarchical Structure Code" id="1005"
              sequence="1"
              description="Code indicating the hierarchical application structure of a transaction set that utilizes the HL segment to define the structure of the transaction set"
              type="ID" required="M"
              minLength="4" maxLength="4"
              idListFile="IDList1005.xml"
              xmlTag="hierarchicalStructureCode"/>
            <dataElement name="Transaction Set Purpose Code" id="353"
              sequence="2"
              description="Code identifying purpose of transaction set"
              type="ID" required="M"
              minLength="2" maxLength="2"
              idListFile="IDList353.xml"
              xmlTag="transactionSetPurposeCode"/>
            <dataElement name="Reference Identification" id="127"
              sequence="3"
              description="Reference information as defined for a particular Transaction Set or as specified by the Reference Identification Qualifier"
              type="AN" required="O"
              minLength="1" maxLength="30"
              xmlTag="referenceIdentification"/>
            <dataElement name="Date" id="373"
              sequence="4"
              description="Date expressed as CCYYMMDD"
              type="DT" required="O"
              minLength="8" maxLength="8"
              xmlTag="date"/>
            <dataElement name="Time" id="337"
              sequence="5"
              description="Time expressed in 24-hour clock time as follows: HHMM, or HHMMSS, or HHMMSSD, or HHMMSSDD, where H = hours (00-23), M = minutes (00-59), S = integer seconds (00-59) and DD = decimal seconds; decimal seconds are expressed as follows: D = tenths (0-9) and DD = hundredths (00-99)"
              type="TM" required="O"
              minLength="4" maxLength="8"
              xmlTag="time"/>
            <dataElement name="Transaction Type Code" id="640"
              sequence="6"
              description="Code specifying the type of transaction"
              type="ID" required="O"
              minLength="2" maxLength="2"
              idListFile="IDList640.xml"
              xmlTag="transactionTypeCode"/>
        </segment>
    </table>
    <table section="detail">
        <segment name="Hierarchical Level" id="HL"
          description="To identify dependencies among and the content of hierarchically related groups of data segments"
          sequence="10"
          occurs="-1"
          required='M'
          xmlTag="HierarchicalLevel">
            <dataElement name="Hierarchical ID Number" id="628"
              sequence="1"
              description="A unique number assigned by the sender to identify a particular data segment in a hierarchical structure"
              type="AN" required="M"
              minLength="1" maxLength="12"
              xmlTag="hierarchicalIdNumber"/>
            <dataElement name="Hierarchical Parent ID Number" id="734"
              sequence="2"
              description="Identification number of the next higher hierarchical data segment that the data segment being described is subordinate to"
              type="AN" required="O"
              minLength="1" maxLength="12"
              xmlTag="hierarchicalParentIdNumber"/>
            <dataElement name="Hierarchical Level Code" id="735"
              sequence="3"
              description="Code defining the characteristic of a level in a hierarchical structure"
              type="ID" required="M"
              minLength="1" maxLength="2"
              idListFile="IDList735.xml"
              xmlTag="hierarchicalLevelCode"/>
            <dataElement name="Hierarchical Child Code" id="736"
              sequence="4"
              description="Code indicating if there are hierarchical child data segments subordinate to the level being described"
              type="ID" required="O"
              minLength="1" maxLength="1"
              idListFile="IDList736.xml"
              xmlTag="hierarchicalChildCode"/>
            <segment name="Trace" id="TRN"
              description="To uniquely identify a transaction to an application"
              sequence="20"
              occurs="9"
              required='O'
              xmlTag="Trace">
                <dataElement name="Trace Type Code" id="481"
                  sequence="1"
                  description="Code identifying which transaction is being referenced"
                  type="ID" required="M"
                  minLength="1" maxLength="2"
                  idListFile="IDList481.xml"
                  xmlTag="traceTypeCode"/>
                <dataElement name="Reference Identification" id="127"
                  sequence="2"
                  description="Reference information as defined for a particular Transaction Set or as specified by the Reference Identification Qualifier"
                  type="AN" required="M"
                  minLength="1" maxLength="30"
                  xmlTag="referenceIdentification"/>
                <dataElement name="Originating Company Identifier" id="509"
                  sequence="3"
                  description="A unique identifier designating the company initiating the funds transfer instructions. The first character is one-digit ANSI identification code designation (ICD) followed by the nine-digit identification number which may be an IRS employer identification number (EIN), data universal numbering system (DUNS), or a user assigned number; the ICD for an EIN is 1, DUNS is 3, user assigned number is 9"
                  type="AN" required="O"
                  minLength="10" maxLength="10"
                  xmlTag="originatingCompanyIdentifier"/>
                <dataElement name="Reference Identification" id="127"
                  sequence="4"
                  description="Reference information as defined for a particular Transaction Set or as specified by the Reference Identification Qualifier"
                  type="AN" required="O"
                  minLength="1" maxLength="30"
                  xmlTag="referenceIdentification"/>
            </segment>
            <segment name="Request Validation" id="AAA"
              description="To specify the validity of the request and indicate follow-up action authorized"
              sequence="25"
              occurs="9"
              required='O'
              xmlTag="RequestValidation">
                <dataElement name="Yes/No Condition or Response Code" id="1073"
                  sequence="1"
                  description="Code indicating a Yes or No condition or response"
                  type="ID" required="M"
                  minLength="1" maxLength="1"
                  idListFile="IDList1073.xml"
                  xmlTag="yesNoConditionOrResponseCode"/>
                <dataElement name="Agency Qualifier Code" id="559"
                  sequence="2"
                  description="Code identifying the agency assigning the code values"
                  type="ID" required="O"
                  minLength="2" maxLength="2"
                  idListFile="IDList559.xml"
                  xmlTag="agencyQualifierCode"/>
                <dataElement name="Reject Reason Code" id="901"
                  sequence="3"
                  description="Code assigned by issuer to identify reason for rejection"
                  type="ID" required="O"
                  minLength="2" maxLength="2"
